#数据库的配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lightcloud?serverTimezone=UTC

#DataSource配置（使用druid）
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        url-pattern: /druid/*
        reset-enable: false
      filter:
        slf4j:
          enabled: true
        wall:
          enabled: true
          db-type: mysql
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 1000
 #thymleaf模板
  thymeleaf:
    enabled: true



#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#上传的文件的文件路径
myfile:
  filepath: 'D:\\A\\upload'
